---
services:
  sql:
    image: postgres:16
    restart: on-failure
    ports:
      - 5432:5432
    volumes:
      - ~/.postgres-multi-money:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: please01
      POSTGRES_USER: adm_user
      POSTGRES_DB: adm_user
    healthcheck:
      test: ["CMD-SHELL", "PGPASSWORD=please01 sh -c 'pg_isready -U adm_user -d adm_user'"]
      interval: 10s
      retries: 60

  sql-init:
    image: multi-money-util
    build:
      target: util
    command: lein do init-sql, migrate
    depends_on:
      sql:
        condition: service_healthy
    volumes:
      - ./config/integration:/usr/local/src/multi-money/config/dev
      - ./logs/sql-init-tmp:/tmp

  mongo:
    image: mongo:7.0
    restart: on-failure
    ports:
      - 27017:27017
    volumes:
      - ~/.mongodb:/etc/mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: adm_user
      MONGO_INITDB_ROOT_PASSWORD: please01
    healthcheck:
      test:
        [
          "CMD",
          "mongo",
          "--quiet",
          "127.0.0.1/test",
          "--eval",
          "'quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)'"
        ]

  mongo-init:
    image: multi-money-util
    build:
      target: util
    command: lein do init-mongo, index-mongo
    depends_on:
      sql:
        condition: service_healthy
    volumes:
      - ./config/integration:/usr/local/src/multi-money/config/dev

  memcached:
    image: memcached:1.6-bullseye
    ports:
      - 11211:11211
    restart: on-failure
    healthcheck:
      test: echo stats | nc 127.0.0.1 11211
      interval: 10s
      retries: 60

  datomic-sql-init:
    image: multi-money-util
    build:
      target: util
    command: ./scripts/datomic-init.sh
    environment:
      SQL_HOST: sql
      SQL_ADM_USER: adm_user
      SQL_ADM_PASSWORD: please01
    depends_on:
      sql:
        condition: service_healthy

  datomic-transactor:
    depends_on:
      sql:
        condition: service_healthy
      memcached:
        condition: service_started
    image: dgknght/datomic-pro:1.0.7075
    volumes:
      - ./logs/datomic-transactor:/datomic-pro/log
      - ./docker-compose/datomic-transactor:/opt/datomic-pro/config
    command: ./bin/transactor ./config/transactor.properties
    restart: on-failure
    ports:
      - 4334:4334
      - 9999:9999
    healthcheck:
      test: wget localhost:9999/health
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 5s

  datomic-console:
    image: dgknght/datomic-pro:1.0.7075
    depends_on:
      datomic-transactor:
        condition: service_healthy
    restart: on-failure
    ports:
      - 8080:8080
    command: ./bin/console -p 8080 sql "datomic:sql://?jdbc:postgresql://sql:5432/datomic?user=app_user&password=please03"

  datomic-peer-server:
    depends_on:
      datomic-transactor:
        condition: service_healthy
      sql:
        condition: service_healthy
    image: dgknght/datomic-pro:1.0.7075
    restart: on-failure
    volumes:
      - ./logs/datomic-peer-server:/datomic-pro/log
    ports:
      - 8998:8998
    command:
      - ./bin/run
      - -m
      - datomic.peer-server
      - -h
      - localhost
      - -p
      - "8998"
      - -Ddatomic.memcachedServers=memcached:11211
      - -a
      - dev-access-key,dev-secret
      - -d
      - money_development,datomic:sql://money_development?jdbc:postgresql://sql:5432/datomic?user=app_user&password=please03
    healthcheck:
      test: ["CMD", "curl", "-k", "https://localhost:8998/health"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 10s
