---
volumes:
  sql-data:
  mongo-data:
  maven-data:
services:
  sql:
    profiles:
      - sql
      - datomic-peer
      - datomic-client
      - all
    image: postgres:16
    restart: on-failure
    ports:
      - 5432:5432
    volumes:
      - type: volume
        source: sql-data
        target: /var/lib/postgresql/data
    environment:
      PGPASSWORD: please01
      POSTGRES_PASSWORD: please01
      POSTGRES_USER: adm_user
      POSTGRES_DB: adm_user
      LOG_STATEMENT: all
      LOG_MIN_MESSAGES: INFO
    healthcheck:
      test: pg_isready -U adm_user -d adm_user
      interval: 3s
      retries: 10

  lein-deps:
    image: multi-money-util
    command: lein deps
    volumes:
      - type: volume
        source: maven-data
        target: /root/.m2

  sql-init:
    profiles:
      - sql
      - datomic-peer
      - datomic-client
      - all
    image: multi-money-util
    build:
      target: util
    command: lein with-profile +util,+docker init-sql
    depends_on:
      sql:
        condition: service_healthy
      lein-deps:
        condition: service_completed_successfully
    volumes:
      - type: bind
        source: ./docker-compose/dev/config
        target: /usr/src/multi-money/config
        read_only: true
      - type: bind
        source: ./logs/sql-init-tmp
        target: /tmp
        read_only: false
      - type: volume
        source: maven-data
        target: /root/.m2
    environment:
      SQL_HOST: sql

  mongo:
    profiles:
      - mongo
      - all
    image: mongo:7.0
    restart: on-failure
    ports:
      - 27017:27017
    volumes:
      - type: volume
        source: mongo-data
        target: /data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: adm_user
      MONGO_INITDB_ROOT_PASSWORD: please01
    healthcheck:
      test:
        - CMD-SHELL
        - "echo \"quit(db.runCommand('ping').ok ? 0 : 2)\""
        - "|"
        - mongosh
        - "127.0.0.1/test"
        - "--quiet"
      interval: 3s
      retries: 10

  mongo-init:
    profiles:
      - mongo
      - all
    image: multi-money-util
    build:
      target: util
    command: lein with-profile +util,+docker do init-mongo, index-mongo
    depends_on:
      mongo:
        condition: service_healthy
      lein-deps:
        condition: service_completed_successfully
    volumes:
      - type: bind
        source: ./docker-compose/dev/config
        target: /usr/src/multi-money/config
        read_only: true
      - type: volume
        source: maven-data
        target: /root/.m2
    environment:
      MONGO_HOST: mongo

  memcached:
    profiles:
      - datomic-peer # Is this needed in the peer profile?
      - datomic-client
      - all
    image: memcached:1.6-bullseye
    ports:
      - 11211:11211
    restart: on-failure
    healthcheck:
      test: echo stats | nc 127.0.0.1 11211
      interval: 10s
      retries: 60

  datomic-sql-init:
    profiles:
      - datomic-peer
      - datomic-client
      - all
    image: multi-money-util
    build:
      target: util
    command: ./scripts/datomic-init.sh
    environment:
      SQL_HOST: sql
      SQL_ADM_USER: adm_user
      SQL_ADM_PASSWORD: please01
      PGPASSWORD: please01
    depends_on:
      sql:
        condition: service_healthy

  datomic-transactor:
    profiles:
      - datomic-peer
      - datomic-client
      - all
    depends_on:
      datomic-sql-init:
        condition: service_completed_successfully
      memcached:
        condition: service_started
    image: dgknght/datomic-pro:1.0.7075
    volumes:
      - type: bind
        source: ./logs/datomic-transactor
        target: /opt/datomic-pro/log
        read_only: false
      - type: bind
        source: ./docker-compose/dev/datomic-transactor
        target: /opt/datomic-pro/config
        read_only: true
    command: ./bin/transactor ./config/transactor.properties
    restart: on-failure
    ports:
      - 4334:4334
      - 9999:9999
    healthcheck:
      test: wget localhost:9999/health
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 5s

  datomic-schema:
    profiles:
      - datomic-peer
      - datomic-client
      - all
    image: multi-money-util
    build:
      target: util
    command: lein with-profile +util,+docker datomic-schema
    volumes:
      - type: bind
        source: ./docker-compose/dev/config
        target: /usr/src/multi-money/config
        read_only: true
      - type: bind
        source: ./logs/datomic-schema-tmp
        target: /tmp
        read_only: false
      - type: volume
        source: maven-data
        target: /root/.m2
    depends_on:
      datomic-transactor:
        condition: service_healthy
      lein-deps:
        condition: service_completed_successfully
    environment:
      DATOMIC_STORAGE_URI: datomic:sql://money_development?jdbc:postgresql://sql:5432/datomic?user=app_user&password=please03
      SQL_HOST: sql

  datomic-console:
    profiles:
      - datomic-peer
      - datomic-client
      - all
    image: dgknght/datomic-pro:1.0.7075
    depends_on:
      datomic-transactor:
        condition: service_healthy
    restart: on-failure
    ports:
      - 8080:8080
    command: ./bin/console -p 8080 sql "datomic:sql://?jdbc:postgresql://sql:5432/datomic?user=app_user&password=please03"

  datomic-peer-server:
    profiles:
      - datomic-client
      - all
    depends_on:
      datomic-schema:
        condition: service_completed_successfully
    image: dgknght/datomic-pro:1.0.7075
    restart: on-failure
    volumes:
      - type: bind
        source: ./logs/datomic-peer-server
        target: /opt/datomic-pro/log
        read_only: false
    ports:
      - 8998:8998
    command:
      - ./bin/run
      - -m
      - datomic.peer-server
      - -h
      - datomic-peer-server
      - -p
      - "8998"
      - -Ddatomic.memcachedServers=memcached:11211
      - -a
      - dev-access-key,dev-secret
      - -d
      - money_development,datomic:sql://money_development?jdbc:postgresql://sql:5432/datomic?user=app_user&password=please03
    healthcheck:
      test: ["CMD", "curl", "-k", "https://localhost:8998/health"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 10s
