---
version: "3.9"
services:
  sql:
    image: postgres:16
    restart: on-failure
    ports:
      - 5432:5432
    volumes:
      - ~/.postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: please01
      POSTGRES_USER: adm_user
      POSTGRES_DB: adm_user
    healthcheck:
      test: ["CMD-SHELL", "PGPASSWORD=please01 sh -c 'pg_isready -U adm_user -d adm_user'"]

  mongo:
    image: mongo:7.0
    restart: on-failure
    ports:
      - 27017:27017
    volumes:
      - ~/.mongodb:/etc/mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: adm_user
      MONGO_INITDB_ROOT_PASSWORD: please01

  memcached:
    image: memcached:1.6-bullseye
    ports:
      - 11211:11211
    restart: on-failure
    depends_on:
      sql:
        condition: service_started

  datomic-transactor:
    depends_on:
      sql:
        condition: service_healthy
      memcached:
        condition: service_started
    image: datomic-pro-transactor
    build:
      context: ./docker-compose/datomic-transactor
    restart: on-failure
    ports:
      - 4334:4334
      - 9999:9999
    healthcheck:
      test: wget localhost:9999/health
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 5s

  datomic-console:
    image: datomic-pro:1.0.7075
    depends_on:
      datomic-transactor:
        condition: service_healthy
      sql:
        condition: service_healthy
    restart: on-failure
    ports:
      - 8080:8080
    command: /datomic-pro/bin/console -p 8080 sql "datomic:sql://?jdbc:postgresql://sql:5432/datomic?user=app_user&password=please03"

  datomic-peer-server:
    depends_on:
      datomic-transactor:
        condition: service_healthy
      sql:
        condition: service_healthy
    image: datomic-pro:1.0.7075
    restart: on-failure
    ports:
      - 8998:8998
    command:
      - /datomic-pro/bin/run
      - -m
      - datomic.peer-server
      - -h
      - localhost
      - -p
      - "8998"
      - -Ddatomic.memcachedServers=memcached:11211
      - -a
      - dev-access-key,dev-secret
      - -d
      - money_development,datomic:sql://money_development?jdbc:postgresql://sql:5432/datomic?user=app_user&password=please03
    healthcheck:
      test: ["CMD", "curl", "-k", "https://localhost:8998/health"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 10s
