---
services:
  web:
    image: dgknght/multi-money-web
    ports:
      - "3010:3000"
    secrets:
      - config
    environment:
      - CONFIG=/run/secrets/config
    links:
      - sql
      - migration
  migration:
    image: dgknght/multi-money-migrate
    secrets:
      - config
    environment:
      - CONFIG=/run/secrets/config
    links:
      - sql
  sql:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_PASSWORD: please01
      POSTGRES_USER: app_user
      POSTGRES_DB: multi_money
secrets:
  config:
    file: config/integration/config.edn
