---
services:
  sql:
    image: postgres:16
    restart: on-failure
    ports:
      - 5432:5432
    volumes:
      - ~/.volumes/multi-money-integration/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: please01
      POSTGRES_USER: adm_user
      POSTGRES_DB: adm_user
      LOG_STATEMENT: all
      LOG_MIN_MESSAGES: INFO
    healthcheck:
      test: ["CMD-SHELL", "PGPASSWORD=please01 sh -c 'pg_isready -U adm_user -d adm_user'"]
      interval: 10s
      retries: 60

  sql-init:
    image: multi-money-util
    build:
      context: ../../
      target: util
    command: lein with-profile +util init-sql
    depends_on:
      sql:
        condition: service_healthy
    volumes:
      - ./config:/usr/local/src/multi-money/config
      - ./logs/sql-init-tmp:/tmp
      - ~/.volumes/multi-money/maven:/root/.m2

  mongo:
    image: mongo:7.0
    restart: on-failure
    ports:
      - 27017:27017
    volumes:
      - ~/.volumes/multi-money-integration/mongodb:/etc/mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: adm_user
      MONGO_INITDB_ROOT_PASSWORD: please01
    healthcheck:
      test:
        - CMD-SHELL
        - "echo \"quit(db.runCommand('ping').ok ? 0 : 2)\""
        - "|"
        - mongosh
        - "127.0.0.1/test"
        - "--quiet"
      interval: 10s
      retries: 60

  mongo-init:
    image: multi-money-util
    build:
      context: ../../
      target: util
    command: lein with-profile +util do init-mongo, index-mongo
    depends_on:
      mongo:
        condition: service_healthy
    volumes:
      - ./config:/usr/local/src/multi-money/config
      - ~/.volumes/multi-money/maven:/root/.m2
    environment:
      MONGO_HOST: mongo

  memcached:
    image: memcached:1.6-bullseye
    ports:
      - 11211:11211
    restart: on-failure
    healthcheck:
      test: echo stats | nc 127.0.0.1 11211
      interval: 10s
      retries: 60

  datomic-sql-init:
    image: multi-money-util
    build:
      context: ../../
      target: util
    command: ./scripts/datomic-init.sh
    environment:
      SQL_HOST: sql
      SQL_ADM_USER: adm_user
      SQL_ADM_PASSWORD: please01
    depends_on:
      sql-init:
        condition: service_completed_successfully

  datomic-transactor:
    depends_on:
      datomic-sql-init:
        condition: service_completed_successfully
      memcached:
        condition: service_started
    image: dgknght/datomic-pro:1.0.7075
    volumes:
      - ./logs/datomic-transactor:/datomic-pro/log
      - ./datomic-transactor:/opt/datomic-pro/config
    command: ./bin/transactor ./config/transactor.properties
    restart: on-failure
    ports:
      - 4334:4334
      - 9999:9999
    healthcheck:
      test: wget localhost:9999/health
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 5s

  datomic-schema:
    image: multi-money-util
    build:
      context: ../../
      target: util
    command: lein with-profile +util datomic-schema
    volumes:
      - ./config:/usr/local/src/multi-money/config
      - ./logs/datomic-schema-tmp:/tmp
      - ~/.volumes/multi-money/maven:/root/.m2
    depends_on:
      datomic-transactor:
        condition: service_healthy
    environment:
      DATOMIC_STORAGE_URI: datomic:sql://money_integration?jdbc:postgresql://sql:5432/datomic?user=app_user&password=please03
      SQL_HOST: sql

  datomic-console:
    image: dgknght/datomic-pro:1.0.7075
    depends_on:
      datomic-transactor:
        condition: service_healthy
    restart: on-failure
    ports:
      - 8080:8080
    command: ./bin/console -p 8080 sql "datomic:sql://?jdbc:postgresql://sql:5432/datomic?user=app_user&password=please03"

  datomic-peer-server:
    depends_on:
      datomic-schema:
        condition: service_completed_successfully
    image: dgknght/datomic-pro:1.0.7075
    restart: on-failure
    volumes:
      - ./logs/datomic-peer-server:/datomic-pro/log
    ports:
      - 8998:8998
    command:
      - ./bin/run
      - -m
      - datomic.peer-server
      - -h
      - datomic-peer-server
      - -p
      - "8998"
      - -Ddatomic.memcachedServers=memcached:11211
      - -a
      - integration-access-key,integration-secret
      - -d
      - money_integration,datomic:sql://money_integration?jdbc:postgresql://sql:5432/datomic?user=app_user&password=please03
    healthcheck:
      test: ["CMD", "curl", "-k", "https://localhost:8998/health"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 10s

  web:
    image: multi-money-web
    build:
      context: ../../
    command: java clojure.main -m multi-money.server
    environment:
      CLASSPATH: /opt/multi-money/config:/opt/multi-money/multi-money.jar
    depends_on:
      datomic-peer-server:
        condition: service_healthy
      mongo:
        condition: service_healthy
    volumes:
      - ./config:/opt/multi-money/config
      - ~/.volumes/multi-money/maven:/root/.m2
