name: Clojure CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Install server-side dependencies
        run: lein deps

      - name: Install clj-kondo
        uses: DeLaGuardo/setup-clj-kondo@master
        with:
          version: '2020.04.05'

      - name: Run linter
        run: clj-kondo --lint src:test --dependencies

      - name: Run server-side tests
        run: lein with-profile test cloverage

      - name: Install client-side dependencies
        run: npm install

      - name: Run client-side tests
        run: lein fig:test

      - name: Create the uberjar
        run: lein uberjar

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log into docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract tags and labels
        id: meta
        uses: docker/metadata-action@v5.4.0
        with:
          images: dgknght/multi-money

      - name: Build and push the docker image
        uses: docker/build-push-action@v5.1.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.output.labels }}
